
console.log("🚀 Real-Time Chat Development Setup")
console.log("=====================================")
console.log("")
console.log("To run the complete application, you need TWO terminals:")
console.log("")
console.log("📟 Terminal 1 - Backend Server:")
console.log("   npm run backend")
console.log("   (Starts WebSocket + API server on port 8080)")
console.log("")
console.log("🌐 Terminal 2 - Frontend Server:")
console.log("   npm run dev")
console.log("   (Starts Next.js frontend on port 3000)")
console.log("")
console.log("🔗 Then open: http://localhost:3000")
console.log("")
console.log("💡 Tip: Keep both terminals open during development")
console.log("=====================================")
